POST http://localhost:4001/api/diseases/update
content-type: application/json

{
    "disease_name": "yellow leaf curl",
     "description": "This is one of more than a dozen plant viruses that can infect tomatoes in both the home garden and commercial production. The virus is physically spread plant-to-plant by the silverleaf whitefly. These insects can acquire this virus in 15-30 minutes during a feeding period on an infected plant.",
    "symptoms_and_signs": "Typical symptoms for this disease in tomato are yellow (chlorotic) leaf edges, upward leaf cupping, leaf mottling, reduced leaf size, and flower drop. TYLCV can have a severe impact on tomato production. Plants infected at an early stage won't bear fruit and their growth will be severely stunted.TYLCV identification based only on symptomatology is unreliable, because similar symptoms can be caused by other viruses or various growing conditions.",
    "treatment": "Spraying fungicides is the most effective way to prevent late blight. For conventional gardeners and commercial producers, protectant fungicides such as chlorothalonil (e.g., Bravo, Echo, Equus, or Daconil) and Mancozeb (Manzate) can be used.
    Continue weekly spray applications to protect plants from further infection. Severely infected plants can be rogued and either buried or burned. Avoid composting diseased plants.
     Rotate tomatoes with vegetables unrelated botanically to tomatoes or potatoes. Do not plant these sites with these groups of vegetables for two to three years. Avoid harvesting tomato fruits with visible disease lesions.",
    "id": 4
}
########

POST http://localhost:4001/api/diseases
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6ImFyY2hAZ21haWwuY29tIiwiaWF0IjoxNjY2ODc2MzYzLCJleHAiOjE2NjY4Nzk5NjN9.O1QLf_MpWqi8V7_mtKtGa2Ge1nwwxML0bT3XjUP7heM

{
    "disease_name": "yellow leaf curl"
    
}

###
GET http://localhost:4001/api/forms/register
 content-type: application/json
 

###
POST http://localhost:4001/api/forms/register/create
content-type: application/json

{

"username": "lol",
"email": "arch2@yahoo.com",
"password": "123"


}

###

POST http://localhost:4001/api/forms/register/delete
content-type: application/json

{
"id": 7

}



 ###
###
GET http://localhost:4001/api/health_status
content-type: application/json
 


###

POST http://localhost:4001/api/health_status/update
content-type: application/json

{
"diagnosis": "Early blight",
"picture_name": "img1.png",
"id": 1
}

###



POST http://localhost:4001/api/health_status/create
content-type: application/json

{
"diagnosis": "Healthy",
"picture_name": "img6.png",
"id": 6
}



###

POST http://localhost:4001/api/health_status/delete
content-type: application/json

{
"id": 6

}

###

GET http://localhost:4001/api/customer
content-type: application/json

###

POST http://localhost:4001/api/customer/update
content-type: application/json

{
"first_name": "ange2",
"last_name": "Mulaudzi",
"email": "angel@gmail.com",
"manager": 1,
"id": 3
}

###
POST http://localhost:4001/api/customer/create
content-type: application/json

{
"first_name": "blight1",
"last_name": "early",
"email": "blight@gmail",
"username": "201701@mail",
"password": "magala.01",
"contacts": "06754346",
"manager": 4,
"id": 2
}

###

POST http://localhost:4001/api/customer/delete
content-type: application/json

{
"id": 7

}

###

GET http://localhost:4001/api/manager
content-type: application/json

###

POST http://localhost:4001/api/manager/update
content-type: application/json

{

"first_name": "Angel",
"last_name": "Magavha",
"email": "angel@gmail.com",
"username": "angel@gmail.com",
"password": "angel@gmail.com",
"contacts":566777,
"id": 1

}


###

POST http://localhost:4001/api/manager/create
content-type: application/json

{
"first_name": "blight",
"last_name": "early",
"email": "blight@gmail",
"username": "201701@mail",
"password": "magala.01",
"contacts": "06754346",
"id": 2

}

###

POST http://localhost:4001/api/manager/delete
content-type: application/json

{
"id": 7

}

###

GET http://localhost:4001/api/projects
content-type: application/json


###

POST http://localhost:4001/api/projects/update
content-type: application/json

{
"project_name": "bunting2",
"location": "gauteng",
"manager_id": 1,
"id": 1
}

###

POST http://localhost:4001/api/projects/create
content-type: application/json

{
"project_name": "Mashamba",
"location": "img3.png",
"manager_id": "3"

}

###

POST http://localhost:4001/api/projects/delete
content-type: application/json

{
"id": 23

}

###

GET http://localhost:4001/api/detect
content-type: application/json


###

POST http://localhost:4001/api/detect/update
content-type: application/json

{
"detect_date": "04/May",
"id": 1
}

###

POST http://localhost:4001/api/detect/create
content-type: application/json

{
"detect_time": "12H00",
"detect_date": "07/March",
"project_id": 1, 
"customer_id": 1, 
"health_status_id": 1

}

###

POST http://localhost:4001/api/detect/delete
content-type: application/json

{
    
"id": 1

}

###
POST http://localhost:4001/api/forms/login
content-type: application/json

{
    "email" : "pa@yahoo.com",
    "password" : "24956"
    
}









####

GET http://localhost:6089/
content-type: application/json